version: "3.8"

services:
  api:
    container_name: api
    build:
      context: docker/api
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - email_sender
      - celery_tasks
      - db
    ports:
      - ${API_PORT}:8000
    volumes:
      - ./app/api:/app/api
      - ./app/alembic:/app/alembic
      - ./app/alembic.ini:/app/alembic.ini
    env_file:
      - .env

  email_sender:
    container_name: email_sender
    build:
      context: docker/email_sender
      dockerfile: Dockerfile
    depends_on:
      - pubsub_redis
    volumes:
      - ./app/email_sender:/app/email_sender
    env_file:
      - .env

  celery_tasks:
    container_name: celery_tasks
    build:
      context: docker/celery_tasks
      dockerfile: Dockerfile
    depends_on:
      - pubsub_redis
      - celery_redis
    volumes:
      - ./app/celery_tasks:/app/celery_tasks
    env_file:
      - .env

  db:
    container_name: db
    image: postgres:latest
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  pubsub_redis:
    container_name: pubsub_redis
    image: redis:latest
    restart: always
    ports:
      - 6379:${REDIS_PORT}
    volumes:
      - pubsub_redis_data:/data

  celery_redis:
    container_name: celery_redis
    image: redis:latest
    restart: always
    ports:
      - 6380:${REDIS_PORT}
    volumes:
      - celery_redis_data:/data

  celery_flower:
    container_name: celery_flower
    build:
      context: docker/celery_tasks
      dockerfile: Dockerfile
    command: celery -A celery_tasks.tasks flower --address=0.0.0.0 --port=5555
    environment:
      - CELERY_BROKER_URL=redis://${CELERY_REDIS_HOST}:${REDIS_PORT}/0
    volumes:
      - ./app/celery_tasks:/app/celery_tasks
      - flower_data:/data
    ports:
      - ${FLOWER_PORT}:5555
    depends_on:
      - celery_tasks
      - celery_redis
    env_file:
      - .env

volumes:
  postgres_data:
  pubsub_redis_data:
  celery_redis_data:
  flower_data:
