version: "3.8"

services:
  api:
    container_name: api
    restart: always
    build:
      context: docker/api
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - ${API_PORT}:8000
    volumes:
      - ./app/api:/app/api
      - ./app/alembic:/app/alembic
      - ./app/alembic.ini:/app/alembic.ini
    env_file:
      - .env

  db:
    container_name: db
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - ${REDIS_PORT}:6379
    env_file:
      - .env

  worker:
    container_name: worker
    build:
      context: docker/api
      dockerfile: Dockerfile
    command: celery -A api.celery_tasks.tasks worker --loglevel=INFO --pool=solo
    volumes:
      - ./app/api:/app/api
    depends_on:
      - redis
    env_file:
      - .env

  flower:
    container_name: flower
    build:
      context: docker/api
      dockerfile: Dockerfile
    command: celery -A api.celery_tasks.tasks flower --address=0.0.0.0 --port=5555
    environment:
      - CELERY_BROKER_URL=redis://${REDIS_HOST}:${REDIS_PORT}/0
    volumes:
      - ./app/api:/app/api
      - flower_data:/data
    ports:
      - ${FLOWER_PORT}:5555
    depends_on:
      - worker
      - redis
    env_file:
      - .env
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  flower_data:
    driver: local